package com.nis.comm.constants;

public class b {
	public static String hospName;
	public static String es;
	public static String eA = "GBK";
	public static String eB = "admin";
	public static String eC = "fcadmin";
	public static final String eD = "!@#:@$_";
	public static final String eE = "user";
	public static final String eF = "message";
	public static final String eG = "zg_dept";
	public static final String eH = "user_menus";
	public static final String eI = "user_json";
	public static final String eJ = "user_menus_json";
	public static final String eK = "user_login_error_num_";
	public static final String eL = "user_login_repeat_error_num_";
	public static final String eM = "user_reg_sms_code_";
	public static final String eN = "user_reg_sms_phone_";
	public static final String eO = "SSO_COOKIE";
	public static final String er = "success";
	public static final String ERROR = "error";
	public static final String eP = "redirect:/error.jsp";
	public static final String eQ = "redirect:/501.jsp";
	public static final String eR = "error_not_login";
	public static final String eS = "redirect:/404.jsp";
	public static final String eT = "redirect:/index.jsp";
	public static final String eU = "hospitalPhoto";
	public static final int eV = 5;
	public static final String eW = "depPhoto";
	public static final int eX = 5;
	public static final String eY = "docPhoto";
	public static final int eZ = 5;
	public static String fa = "123456";
	public static final Integer fb = Integer.valueOf(50);
	public static final String fd = "doc_position";
	public static final String fe = "gender";
	public static final String ff = "sms_platform";
	public static String dataForm = "病程";
	public static String fg = "FX00001";
	public static String dybw = "血液";
	public static String fh = "白蛋白";
	public static String fi = "感控小智";
}